name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write permission for pushing updates to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          check-latest: false

      - name: Generate Javadoc
        run: |
          javadoc -d javadoc -sourcepath lib/src/main/java -subpackages com.redshock.algorithmia  # Adjust the package name and source path

      - name: Rename javadoc folder
        run: |
          mv javadoc/ docs/

        # Configure git user (needed to commit)
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

        # Create a new branch or check out the javadoc branch
      - name: Check out javadoc branch
        run: |
          git fetch origin
          git checkout -b javadoc || git checkout javadoc

        # Add, commit, and push the generated Javadoc files
      - name: Commit and push Javadoc
        run: |
          git add docs/
          git commit -m "Update Javadoc"
          git push origin javadoc --force